---
type: cloudgenix template
version: 1.0
# Created at 2021-04-21T05:47:38.995797Z
# by system_1062@soumya_elcap.com
sites v4.5:
  TEST-SITE-NO-CIRCUITE:
    address:
      city: Mumbai
      country: India
      post_code:
      state: Maharashtra
      street: Malad
      street2:
    admin_state: disabled
    description:
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 18.96667
      longitude: 72.83333
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: Default Path Simple Stack (Simple)
    policy_set_id:
    priority_policysetstack_id: Default QoS Simple Stack (Simple)
    security_policyset_id:
    service_binding: Preset Domain
    tags:
